/**
 * @file splat/io/lcc_writer.h
 * @brief Write LCC (Lixel CyberColor) format files
 *
 * Converts SplatCloud(s) into the LCC file set:
 *   meta.lcc   — JSON metadata
 *   index.bin  — quadtree unit index
 *   data.bin   — packed 32-byte-per-splat records
 *   shcoef.bin — packed 64-byte-per-splat SH coefficients (Quality only)
 */

#pragma once

#include <filesystem>
#include <string>
#include <vector>

namespace splat {

class SplatCloud;

/// Configuration for LCC file output.
struct LccWriteConfig {
  /// Quadtree cell width in metres.
  float cellSizeX = 30.0f;

  /// Quadtree cell height in metres.
  float cellSizeY = 30.0f;

  /// "Quality" enables SH output (shcoef.bin); "Portable" skips it.
  std::string fileType = "Quality";

  /// Scene name (stored in meta.lcc).
  std::string name = "XGrids Splats";

  /// Description string (stored in meta.lcc).
  std::string description = "Generated by SplatLib";

  /// Unique identifier; auto-generated as random 32-hex string when empty.
  std::string guid;

  /// Apply the inverse of the reader's PlayCanvas coordinate transform
  /// so that reading back produces the same SplatCloud columns.
  bool applyCoordinateTransform = true;
};

/**
 * @brief Write LCC files from per-LOD DataTables.
 *
 * Each entry in @p lods corresponds to one LOD level (lod[0] = LOD0, etc.).
 * Column names must match the convention used by readLcc():
 *
 *   Required:  x, y, z, rot_0..rot_3, f_dc_0..f_dc_2,
 *              scale_0..scale_2, opacity
 *   Optional:  nx, ny, nz  (default 0), f_rest_0..f_rest_44 (SH)
 *
 * @param outputDir  Directory where the LCC file set will be written.
 * @param lods       One SplatCloud per LOD level (at least one required).
 * @param config     Output configuration.
 */
void writeLcc(const std::filesystem::path& outputDir, const std::vector<const SplatCloud*>& lods,
              const LccWriteConfig& config = {});

}  // namespace splat
